{% set name = "datasette-copyable" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/datasette-copyable-{{ version }}.tar.gz
  sha256: c0eacfbb14fd255a903f7ee858bea51cae48e7ba9668a38acebeaaecc82db0b4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - datasette >=0.63
    - tabulate

test:
  imports:
    - datasette_copyable
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/simonw/datasette-copyable
  summary: Datasette plugin for outputting tables in formats suitable for copy and paste
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
