schema_version: 1

context:
  name: datasette-copyable
  version: 0.3.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/datasette-copyable-${{ version }}.tar.gz
  sha256: c0eacfbb14fd255a903f7ee858bea51cae48e7ba9668a38acebeaaecc82db0b4

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - datasette >=0.63
    - tabulate

tests:
  - python:
      imports:
        - datasette_copyable
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Datasette plugin for outputting tables in formats suitable for copy and paste
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/simonw/datasette-copyable

extra:
  recipe-maintainers:
    - rxm7706
